language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 14.3

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

install:
  - npm ci

script:
  #- npm run start:ci &
  #- npm run cy:run -- --record --parallel
  - npm run cy:run -- --headless
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true